<script type="text/javascript" src="<?php echo base_url()?>assets/admin/js/apps/master.js"></script><script type="text/javascript" src="<?php echo base_url()?>assets/admin/js/ui.spinner.min.js"></script><script type="text/javascript" src="<?php echo base_url()?>assets/admin/js/chosen.jquery.min.js"></script><script type="text/javascript" src="<?php echo base_url()?>assets/admin/js/jquery.cookie.js"></script><script type="text/javascript" src="<?php echo base_url()?>assets/admin/js/modernizr.min.js"></script><script type="text/javascript" src="<?php echo base_url()?>assets/admin/js/jquery.slimscroll.js"></script><script type="text/javascript" src="<?php echo base_url()?>assets/admin/js/custom.js"></script><script type="text/javascript" src="<?php echo base_url()?>assets/admin/js/forms.js"></script> <div class="rightpanel">                <ul class="breadcrumbs">            <li><a href="dashboard.html"><i class="iconfa-home"></i></a> <span class="separator"></span></li>            <li>Master Management >> View Test</li>                    </ul>                <div class="pageheader">                       <div class="pageicon"><span class="iconfa-book"></span></div>            <div class="pagetitle">            <h5>&nbsp;</h5>                <h1>Mock Test Management</h1>            </div>        </div><!--pageheader-->                <div class="maincontent">            <div class="maincontentinner">            <div class="widgetbox box-inverse">                <h4 class="widgettitle">New Test</h4>                <div class="widgetcontent wc1">                    <form id="moctest_registration" method="post" action="<?php echo base_url()?>master/study_moctest" class="stdform" >         <div class="row-fluid">                        <div class="span6">                            <div class="par control-group">                                                             <label class="control-label" for="firstname">Test Name</label>                <div class="controls"><input type="text" name="test_name" value="<?php echo set_value("test_name");?>" id="test_name" class="input-large" /></div>                <span class="s_country" style="color:red !important; padding-left:45%;"><?php echo form_error("test_name"); ?></span>                                           </div>              <input type="hidden" value="<?php echo $srno;?>" name="testque_testid" id="testque_testid">                            
                            
<div class="par control-group">                                <label class="control-label" for="firstname">Time</label>                                <div class="controls"><input type="text" name="test_time" value="<?php echo set_value("test_time");?>" id="test_time" class="input-large" placeholder="Enter duration for test" /></div>                <span class="s_country" style="color:red !important; padding-left:45%;"><?php echo form_error("test_time"); ?></span>                            </div>

</div>         
                   </div>                    <div class="par control-group">                             <label>Select Question</label>             <span class="field">                            <select name="testque_queid[]" multiple="multiple" class="span4">                                <?php                  $ques=$this->myclass->select("que_id,que_question","question","que_status='Active'");                                   if(is_array($ques) && !empty($ques))                  {                     $i=1;                   foreach( $ques as $list)                    {                     ?>                      <option value="<?php echo $list->que_id?>"><?php echo $i;?>) &nbsp;<?php echo $list->que_question?></option>                                                      <?php                   echo $i++;                    }                                     }                   ?>                            </select>                            </span>              <span class="s_country" style="color:red !important; padding-left:45%;"><?php echo form_error("testque_queid"); ?></span>                                                   </div>                                                                                                        <div class="par control-group">                                    <label class="control-label" for="location">Status</label>                               <span class="field">                            <select name="test_status" class="uniformselect ">                                <option value="Active">Active</option>                                <option value="Inactive">Inactive</option>                            </select>                            </span>                            <span style="color:red !important; padding-left:10px;"><?php echo form_error("test_status"); ?></span>                            </div>
                          <div class="par control-group">                                <label>Paid Test</label>                                <span>                                <input type="radio" name="test_paid" value="Paid"/> Yes                                <input type="radio" name="test_paid" checked="checked" value="Free"/> No                                </span>                            </div> 
                          <p class="stdformbutton"><button class="btn btn-primary">Submit</button>                            </p>                    </form>                </div><!--widgetcontent-->            </div><!--widget-->                      <h4 class="widgettitle">Test List</h4>                <table id="dyntable" class="table table-bordered responsive">                                        <thead>                        <tr>                                                       <th class="head0">Sr No</th> 
                          <th class="head1">Test</th>              
                          <th class="head0">Time</th>             
                          <th class="head0">Status</th> 
                          <th class="head1">Action</th>
                          </tr>                    
                          </thead>                    
                          <tbody>          
                          <?php $uni_list=$this->myclass->select("test_id,test_name,test_time,test_status","test","test_type='moc' ORDER BY test_name");         if(is_array($uni_list) && $uni_list!='no')          {           $i=1;           foreach($uni_list as $list)           {           if($list->test_status=='Active')            {             $status='<span class="label label-success">Active</span>';              }               else            {             $status='<span class="label label-important">Inactive</span>';            }           ?>                        <tr class="gradeX">                          </span></td>                            <td class="center"><?php echo $i; ?></td>                              <td><?php echo $list->test_name;?></td>               <td><?php echo $list->test_time;?></td>              <td class="center"><?php echo $status;?></td>             <td class="center"><a class="deleterow deltopic" id='del-<?php echo $list->test_id;?>' title='Delete Test'><span class="icon-trash"></span></a>&nbsp;&nbsp;&nbsp;<a href='<?php echo base_url()?>master/edit_test/<?php echo $list->test_id;?>' class="icon-pencil" title='Edit Test'></i></a> </td>                        </tr>         <?php             $i++;           }         }             ?>                      </tbody>                </table>                            </div><!--maincontentinner-->        </div><!--maincontent-->            </div><!--rightpanel-->    </div><!--rightpanel-->